# -*- coding: utf-8 -*-
"""Content Based Filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qSlKlpJMrqxUi184hlDODMhZ7wcEglZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

A = pd.read_excel('affordability-gap-data.xlsx')

R = pd.read_excel('college-results.xlsx')

columns_to_filter_A = [
'Unit ID',
'Institution Name',
'City',
'State Abbreviation',
'Sector Name',
'MSI Status',
'HBCU',
'PBI',
'ANNHI',
'TRIBAL',
'AANAPII',
'HSI',
'NANTI',
'Annual Center-Based Child Care Cost',
'Annual Home-Based Child Care Cost'
]

columns_to_filter_R = [
    "UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION",
    # if > than a certain proprotion X_focus -> BOOL
    "Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",
    "Percent of Bachelor Degrees Awarded in Arts and Humanities",
    "Percent of Bachelor Degrees Awarded in Education",
    "Percent of Bachelor Degrees Awarded in Social Sciences",
    "Percent of Bachelor Degrees Awarded in Health Sciences",
    "Percent of Bachelor Degrees Awarded in Business",
    "Percent of Women Undergraduates", # if > than a certain proportion -> women_serving BOOL
    "Average Cost of Attendance In-State",
    "Average In-State Tuition for First-Time, Full-Time Undergraduates",
    "Average Net Price After Grants, 2020-21",
    "Average Net Price for Low-Income Students, 2020-21",
    "Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21",
    "Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",
    "Median Debt of Completers",
    "Median Earnings of Students Working and Not Enrolled 10 Years After Entry",
    "Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21",
    "Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21",
    "Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",
    "Instructional Expenditures Per Student", # if > than a certain proportion -> high
]

R_filt = R.loc[:, columns_to_filter_R]

# keep colleges with degree awarded data
deg_pct = [
    "Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",
    "Percent of Bachelor Degrees Awarded in Arts and Humanities",
    "Percent of Bachelor Degrees Awarded in Education",
    "Percent of Bachelor Degrees Awarded in Social Sciences",
    "Percent of Bachelor Degrees Awarded in Health Sciences",
    "Percent of Bachelor Degrees Awarded in Business"
]
for deg in deg_pct:
  R_filt = R_filt.dropna(subset=[deg])
  R_filt = R_filt[R_filt[deg]!=0]

def women_serving(percent_of_women):
  if percent_of_women > 63.0:
    return 1
  else:
    return 0

deg_pct = [
    "Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",
    "Percent of Bachelor Degrees Awarded in Arts and Humanities",
    "Percent of Bachelor Degrees Awarded in Education",
    "Percent of Bachelor Degrees Awarded in Social Sciences",
    "Percent of Bachelor Degrees Awarded in Health Sciences",
    "Percent of Bachelor Degrees Awarded in Business"
]
for deg in deg_pct:
  print(deg)
  print(R_filt[deg].mean())

def has_stem_focus(stem):
  # average pct value of stem
  if stem > 0.08033298596491228:
    return 1
  else:
    return 0

def has_arts_focus(arts):
  if arts > 0.03517335614035087:
    return 1
  else:
    return 0

def has_education_focus(educ):
  if educ > 0.06971262807017545:
    return 1
  else:
    return 0

def has_social_sci_focus(socs):
  if socs > 0.049729201754385964:
    return 1
  else:
    return 0

def has_health_focus(health):
  if health> 0.15620096315789472:
    return 1
  else:
    return 0

def has_business_focus(biz):
  if biz > 0.19085154210526314:
    return 1
  else:
    return 0

# 1. STEM
R_filt['has_stem_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math'].apply(has_stem_focus)

# 2. Arts and Humanities
R_filt['has_arts_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Arts and Humanities'].apply(has_arts_focus)

# 3. Education
R_filt['has_education_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Education'].apply(has_education_focus)

# 4. Social Sciences
R_filt['has_social_sci_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Social Sciences'].apply(has_social_sci_focus)

# 5. Health Sciences
R_filt['has_health_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Health Sciences'].apply(has_health_focus)

# 6. Business
R_filt['has_business_focus'] = R_filt['Percent of Bachelor Degrees Awarded in Business'].apply(has_business_focus)

R_filt = R_filt.drop(columns=deg_pct)

R_filt['women_serving'] = R_filt['Percent of Women Undergraduates'].apply(women_serving)
R_filt = R_filt.drop(columns='Percent of Women Undergraduates')

R_filt.info()

col_net_price = 'Average Net Price After Grants, 2020-21'
col_earnings = 'Median Earnings of Students Working and Not Enrolled 10 Years After Entry'
col_debt = 'Median Debt of Completers'

# Total Cost = Annual Net Price * 4
R_filt['Total_Net_Price_4_Years'] = R_filt[col_net_price] * 4

# Metric 1: Payback Period (in Years)
R_filt['Payback_Period_Years'] = np.where(
    R_filt[col_earnings] > 0,
    R_filt['Total_Net_Price_4_Years'] / R_filt[col_earnings],
    np.nan # Set to NaN if earnings are 0 or missing to avoid division by zero
)

# Metric 2: 10-Year ROI (Percentage)
total_10_year_earnings = R_filt[col_earnings] * 10
total_cost = R_filt['Total_Net_Price_4_Years']

R_filt['ROI_10_Year_Pct'] = np.where(
    total_cost > 0,
    ((total_10_year_earnings - total_cost) / total_cost) * 100,
    np.nan # Set to NaN if cost is 0 or missing
)

# Metric 3: Debt-to-Income Ratio
R_filt['Debt_to_Income_Ratio'] = np.where(
    R_filt[col_earnings] > 0,
    R_filt[col_debt] / R_filt[col_earnings],
    np.nan # Set to NaN if earnings are 0 or missing
)

R_filt[[
    col_earnings,
    col_debt,
    'Total_Net_Price_4_Years',
    'Payback_Period_Years',
    'ROI_10_Year_Pct',
    'Debt_to_Income_Ratio'
]].head(10)

R_filt['expenditure_to_tuition_ratio'] = (
    R_filt['Instructional Expenditures Per Student'] / R_filt['Average In-State Tuition for First-Time, Full-Time Undergraduates']
)

sns.histplot(R_filt['expenditure_to_tuition_ratio'])
print(R_filt['expenditure_to_tuition_ratio'].median())

def has_high_expenditure_per_student(ratio):
  if ratio > 0.7320691237192232:
    return 1
  else:
    return 0

R_filt['has_high_expenditure_per_student'] = R_filt['expenditure_to_tuition_ratio'].apply(has_high_expenditure_per_student)

financial_drops = [
 'Average Cost of Attendance In-State',
 'Average In-State Tuition for First-Time, Full-Time Undergraduates',
 'Average Net Price After Grants, 2020-21',
 'Average Net Price for Low-Income Students, 2020-21',
 'Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21',
 'Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21',
 'Median Debt of Completers',
 'Median Earnings of Students Working and Not Enrolled 10 Years After Entry',
 'Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21',
 'Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21',
 'Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years',
]
R_filt = R_filt.drop(columns=financial_drops)

R_filt = R_filt.drop(columns='Instructional Expenditures Per Student')

R_filt.info()

#ns.histplot(R_filt['Instructional Expenditures Per Student'])
IES_trim = R_filt[R_filt['Instructional Expenditures Per Student'] < 40_000]
sns.histplot(IES_trim['Instructional Expenditures Per Student'])
print(IES_trim['Instructional Expenditures Per Student'].mean())

private_for_profit = [
'Private for-profit, less-than 2-year',
'Private for-profit, 2-year',
'Private for-profit, 4-year or above',
]

public = [
'Public, less-than 2-year',
'Public, 2-year',
'Public, 4-year or above',
]

private_not_for_profit = [
'Private not-for-profit, less-than 2-year',
'Private not-for-profit, 2-year',
'Private not-for-profit, 4-year or above',
]

other = [
'Administrative Unit',
'Sector unknown'
]

def add_sector_type(sector_name):
  """
  Rolls up a sector name to a general type
  """
  if sector_name in private_for_profit:
    return 'for profit private'
  elif sector_name in public:
    return 'public'
  elif sector_name in private_not_for_profit:
    return 'not for profit private'
  elif sector_name in other:
    return 'other'

A_filt = A.loc[:, columns_to_filter_A]
A_filt['sector type'] = A_filt['Sector Name'].apply(add_sector_type)

AR = A_filt.merge(R_filt, how='inner', left_on='Unit ID', right_on='UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION')

AR = AR.drop(columns=['UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION','expenditure_to_tuition_ratio','sector type'])

AR['Sector Name'].unique()

AR.info()

AR_numeric_columns = AR.select_dtypes(include='number').columns
AR_object_columns = AR.select_dtypes(include='object').columns

preprocess = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), AR_numeric_columns),
        ("cat", OneHotEncoder(), AR_object_columns)
    ]
)

preprocess.fit(AR)

college_matrix = preprocess.transform(AR)

import pandas as pd
import numpy as np

def get_filtered_colleges(student_profile, ar_dataframe):
    """
    Filters the college DataFrame based on a student's profile dictionary.

    The function filters based on the columns provided by the user.

    Assumptions:
    1. For flag columns (e.g., 'has_stem_focus', 'HBCU', 'women_serving'),
       a value of 1 in the profile means the college MUST have 1.
       If the key is not in the profile, or the value is 0/None,
       it is not used as a filter (i.e., "don't care").

    2. For numeric threshold columns (e.g., 'Total_Net_Price_4_Years'),
       the value in the profile is treated as a MAXIMUM (less than or equal to).

    3. All specified preferences are AND-ed together for the final list.
    """

    # Start with a full copy of the DataFrame to avoid modifying the original
    filtered_df = AR.copy()

    # --- Define Filter Columns ---

    # 1. Flag columns (where 1 means "must match")
    # These are the columns you listed
    flag_cols = [
        'MSI Status', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI',
        'has_stem_focus', 'has_arts_focus', 'has_education_focus',
        'has_social_sci_focus', 'has_health_focus', 'has_business_focus',
        'women_serving'
    ]

    # 2. Threshold columns (where profile value is a max)
    threshold_cols = [
        'Total_Net_Price_4_Years'
    ]

    print("--- Filtering based on profile: ---")

    # --- Apply Flag Filters ---
    for col in flag_cols:
        # Use .get() to safely check if the key exists and is 1
        if student_profile.get(col) == 1:
            print(f"[Applying Filter] {col} == 1")
            filtered_df = filtered_df[filtered_df[col] == 1]

    # --- Apply Threshold Filters ---
    for col in threshold_cols:
        # Check if the key exists and has a non-None value
        if student_profile.get(col) is not None:
            max_val = student_profile[col]
            print(f"[Applying Filter] {col} <= {max_val}")
            # Filter for colleges less than or equal to the max value
            filtered_df = filtered_df[filtered_df[col] <= max_val]

    print("--- Filtering complete. ---")

    # Return the key info of matched colleges
    return filtered_df[['Unit ID', 'Institution Name', 'Total_Net_Price_4_Years']]

# --- EXAMPLE USAGE ---
# This demonstrates how to use the function.
# We will create a small, dummy 'AR' DataFrame for this example.
# In your real code, you would just use your loaded 'AR' DataFrame.

data = {
    'Unit ID': [1001, 1002, 1003, 1004, 1005],
    'Institution Name': ['Flagship U', 'Tech Institute', 'Arts College', 'HBCU Business School', 'State Health College'],
    'has_stem_focus': [1, 1, 0, 0, 0],
    'has_arts_focus': [0, 0, 1, 0, 0],
    'has_business_focus': [0, 0, 0, 1, 0],
    'has_health_focus': [0, 0, 0, 0, 1],
    'HBCU': [0, 0, 0, 1, 0],
    'women_serving': [0, 0, 1, 0, 0],
    'Total_Net_Price_4_Years': [80000, 60000, 70000, 45000, 55000],
    'MSI Status': [0, 0, 0, 1, 0],
    'PBI': [0, 0, 0, 0, 0], 'ANNHI': [0, 0, 0, 0, 0], 'TRIBAL': [0, 0, 0, 0, 0],
    'AANAPII': [0, 0, 0, 0, 0], 'HSI': [0, 0, 0, 0, 0], 'NANTI': [0, 0, 0, 0, 0],
    'has_education_focus': [0, 0, 0, 0, 0], 'has_social_sci_focus': [0, 0, 0, 0, 0]
}
AR_dummy = pd.DataFrame(data)

# --- Define a Student Profile ---
# This student wants a school that is:
# 1. An HBCU
# 2. Has a business focus
# 3. Costs less than $50,000
student_1_profile = {
    'HBCU': 1,
    'has_business_focus': 1,
    'Total_Net_Price_4_Years': 50000
}

print("--- Getting Recommendations for Student 1 ---")
recommendations_1 = get_filtered_colleges(student_1_profile, AR_dummy)
print(recommendations_1)
print("\n")


# --- Define another Student Profile ---
# This student wants:
# 1. A STEM focus
# 2. A budget under $65,000
# 3. 'women_serving' is 0, which we treat as "don't care"
student_2_profile = {
    'has_stem_focus': 1,
    'women_serving': 0,
    'Total_Net_Price_4_Years': 65000
}

print("--- Getting Recommendations for Student 2 ---")
recommendations_2 = get_filtered_colleges(student_2_profile, AR_dummy)
print(recommendations_2)

